name: Configure GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: [".github/workflows/**"]

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
        with:
          # Automatically detect the static HTML files in the repository
          static_site_generator: manual
          token: ${{ secrets.GITHUB_TOKEN }}
